### ISSUE TITLE
pVACseq is deprecated and it is now called pVACtools

### ISSUE THREAD

**Issue by rezakj** [icbi-lab/nextNEOpi#21]
The pipeline went fine all the way until step number 12 and I got this error:

Do you think it's because the pVACseq is deprecated?

`icbi/nextNEOpi execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 1.
The full error message was:
Error executing process > 'pVACseq (sample2)'
Caused by:
  Process `pVACseq (sample2)` terminated with an error exit status (1)
Command executed:
  pvacseq run \
      --iedb-install-directory /opt/iedb \
      -t 10 \
      -p sample2_vep_phased.vcf.gz \
      -e1 8,9,10,11 \
      -e2 15,16,17,18,19,20,21,22,23,24,25 \
      --normal-sample-name sample2_normal \
      --tumor-purity 0.68 \
       \
      --netmhc-stab \
      --binding-threshold 500 --top-score-metric median --minimum-fold-change 0.0 --normal-cov 5 --tdna-cov 10 --trna-cov 10 --normal-vaf 0.02 --tdna-vaf 0.25 --trna-vaf 0.25 --expn-val 1 --maximum-transcript-support-level 1 \
      sample2_vep_somatic_gx.vcf.gz sample2_tumor HLA-B*27:02 NetMHCpan MHCflurry NetMHCIIpan ./
  `

**Comment by rezakj** [comment]
Thank you for the quick response. 

I just saw the log file and it might have been because of the python load error, I fixed the error and will keep you updated after the second run.
Here is the error:

`Downloading nextflow dependencies. It may require a few seconds, please wait .. 
[K[33mNOTE: Nextflow is not tested with Java 1.8.0_292 -- It's recommended the use of version 11 up to 18
(B[m
Downloading nextflow dependencies. It may require a few seconds, please wait .. 
[KError: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/jgit/api/errors/GitAPIException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
Loading python/cpu/2.7.15
  ERROR: python/cpu/2.7.15 cannot be loaded due to a conflict.
    HINT: Might try "module unload miniconda3/gpu/4.9.2" first.
Loading manta/1.6.0
  ERROR: Load of requirement 'python/cpu/2.7.15' failed
`

**Comment by rezakj** [comment]
Issue solved. It was the python error I mentioned. Thank you for the work you for the pipline and the you have done!
