### ISSUE TITLE
pVACSeq chmod error

### ISSUE THREAD

**Issue by zktuong** [icbi-lab/nextNEOpi#56]
Hi,

i'm encountering a chmod issue with pVACSeq:

```
executor >  local (3)
[-        ] process > merge_fastq                    -
[a4/caf946] process > RegionsBedToIntervalList (R... [100%] 1 of 1, cached: 1 ✔
[b1/056e0f] process > BaitsBedToIntervalList (Bai... [100%] 1 of 1, cached: 1 ✔
[ec/107a51] process > preprocessIntervalList (pre... [100%] 1 of 1, cached: 1 ✔
[9b/a0e662] process > SplitIntervals (SplitInterv... [100%] 1 of 1, cached: 1 ✔
[5a/71f069] process > IntervalListToBed (BedFromI... [100%] 1 of 1, cached: 1 ✔
[72/004987] process > ScatteredIntervalListToBed ... [100%] 40 of 40, cached:...
[31/83a609] process > FastQC (sample1 : normal_DNA)  [100%] 3 of 3, cached: 3 ✔
[c8/c97138] process > fastp (sample1 : tumor_RNA)    [100%] 3 of 3, cached: 3 ✔
[c5/8dc5ea] process > FastQC_trimmed (sample1 : n... [100%] 3 of 3, cached: 3 ✔
[ab/1336b4] process > make_uBAM (sample1 : normal... [100%] 2 of 2, cached: 2 ✔
[0e/01fe05] process > Bwa (sample1 : tumor_DNA)      [100%] 2 of 2, cached: 2 ✔
[53/0129cc] process > merge_uBAM_BAM (sample1 : n... [100%] 2 of 2, cached: 2 ✔
[88/2be82e] process > MarkDuplicates (sample1 : t... [100%] 2 of 2, cached: 2 ✔
[d8/5219bb] process > alignmentMetrics (sample1 :... [100%] 2 of 2, cached: 2 ✔
[85/5c3749] process > scatterBaseRecalGATK4 (samp... [100%] 80 of 80, cached:...
[e6/4af5de] process > gatherGATK4scsatteredBQSRta... [100%] 2 of 2, cached: 2 ✔
[f3/28adb1] process > scatterGATK4applyBQSRS (sam... [100%] 80 of 80, cached:...
[3e/2ad287] process > GatherRecalBamFiles (sample... [100%] 2 of 2, cached: 2 ✔
[60/ee77ac] process > GetPileup (sample1 : tumor_... [100%] 2 of 2, cached: 2 ✔
[f2/33c676] process > Mutect2 (sample1)              [100%] 40 of 40, cached:...
[41/366e03] process > gatherMutect2VCFs (sample1)    [100%] 1 of 1, cached: 1 ✔
[18/74008f] process > FilterMutect2 (sample1)        [100%] 1 of 1, cached: 1 ✔
[6f/baa5f5] process > HaploTypeCaller (sample1)      [100%] 40 of 40, cached:...
[38/f1a3d5] process > CNNScoreVariants (sample1)     [100%] 40 of 40, cached:...
[2c/11ce66] process > MergeHaploTypeCallerGermlin... [100%] 1 of 1, cached: 1 ✔
[1d/1f6e90] process > FilterGermlineVariantTranch... [100%] 1 of 1, cached: 1 ✔
[54/644924] process > IndelRealignerIntervals (sa... [100%] 80 of 80, cached:...
[1e/67edb8] process > GatherRealignedBamFiles (sa... [100%] 2 of 2, cached: 2 ✔
[d8/37aa85] process > VarscanSomaticScattered (sa... [100%] 40 of 40, cached:...
[6e/ee3baa] process > gatherVarscanVCFs (sample1)    [100%] 1 of 1, cached: 1 ✔
[34/4ba1f3] process > ProcessVarscan (sample1)       [100%] 1 of 1, cached: 1 ✔
[1a/194a47] process > FilterVarscan (sample1)        [100%] 1 of 1, cached: 1 ✔
[db/564811] process > MergeAndRenameSamplesInVars... [100%] 1 of 1, cached: 1 ✔
[5c/368f2e] process > MantaSomaticIndels (sample1)   [100%] 1 of 1, cached: 1 ✔
[01/827fd1] process > StrelkaSomatic (sample1)       [100%] 1 of 1, cached: 1 ✔
[9f/c2fa83] process > finalizeStrelkaVCF (sample1)   [100%] 1 of 1, cached: 1 ✔
[b6/87b7e4] process > mkHCsomaticVCF (sample1)       [100%] 1 of 1, cached: 1 ✔
[7a/a22406] process > VepTab (sample1)               [100%] 4 of 4, cached: 4 ✔
[6f/ca1acc] process > mkCombinedVCF (sample1)        [100%] 1 of 1, cached: 1 ✔
[92/366e68] process > VEPvcf (sample1)               [100%] 1 of 1, cached: 1 ✔
[f1/620f90] process > ReadBackedphasing (sample1)    [100%] 1 of 1, cached: 1 ✔
[9f/fa19d0] process > AlleleCounter (sample1 : tu... [100%] 2 of 2, cached: 2 ✔
[86/906c05] process > ConvertAlleleCounts (sample1)  [100%] 1 of 1, cached: 1 ✔
[9a/dda444] process > Ascat (sample1)                [100%] 1 of 1, cached: 1 ✔
[e5/9a9916] process > SequenzaUtils (sample1)        [100%] 24 of 24, cached:...
[ef/076d9e] process > gatherSequenzaInput (sample1)  [100%] 1 of 1, cached: 1 ✔
[b6/03945f] process > Sequenza (sample1)             [100%] 1 of 1, cached: 1 ✔
[92/4715cb] process > make_CNVkit_access_file (mk... [100%] 1 of 1, cached: 1 ✔
[3d/31a04c] process > CNVkit (sample1)               [100%] 1 of 1, cached: 1 ✔
[8b/7d847c] process > Clonality (sample1)            [100%] 1 of 1 ✔
[-        ] process > MutationalBurden               [  0%] 0 of 1
[-        ] process > MutationalBurdenCoding         [  0%] 0 of 1
[14/db930e] process > mhc_extract (sample1)          [100%] 1 of 1, cached: 1 ✔
[0a/1c5dcf] process > pre_map_hla (sample1)          [100%] 1 of 1, cached: 1 ✔
[1a/6ee8ce] process > OptiType (sample1)             [100%] 1 of 1, cached: 1 ✔
[b6/419bee] process > pre_map_hla_RNA (sample1)      [100%] 1 of 1, cached: 1 ✔
[ce/fc3ea4] process > OptiType_RNA (sample1)         [100%] 1 of 1, cached: 1 ✔
[99/c0203b] process > run_hla_hd (sample1)           [100%] 1 of 1, cached: 1 ✔
[39/8449b9] process > get_vhla (sample1)             [100%] 1 of 1, cached: 1 ✔
[dd/124d88] process > Neofuse (sample1)              [100%] 1 of 1, cached: 1 ✔
[5e/c28a64] process > publish_NeoFuse (sample1)      [100%] 1 of 1, cached: 1 ✔
[28/88bcd6] process > add_geneID (sample1)           [100%] 1 of 1, cached: 1 ✔
[2b/dea077] process > gene_annotator (sample1)       [100%] 1 of 1, cached: 1 ✔
[74/4f1a5b] process > pVACseq (sample1)              [  9%] 2 of 21, failed: 2
[-        ] process > concat_pVACseq_files           -
[-        ] process > aggregated_reports             -
[57/b3f533] process > pVACtools_generate_protein_... [100%] 1 of 1, cached: 1 ✔
[e1/744bf9] process > pepare_mixMHC2_seq (sample1)   [100%] 1 of 1, cached: 1 ✔
[c6/bca661] process > mixMHC2pred (sample1)          [100%] 1 of 1, cached: 1 ✔
[-        ] process > addCCF                         -
[12/0dcfe2] process > make_epitopes_fasta (sample1)  [100%] 4 of 4, cached: 4
[ab/efd514] process > blast_epitopes (sample1)       [100%] 4 of 4, cached: 4
[41/fc83eb] process > add_blast_hits (sample1)       [100%] 4 of 4, cached: 4
[-        ] process > csin                           -
[-        ] process > immunogenicity_scoring         -
[3a/be5dea] process > mixcr (sample1 : tumor_DNA)    [100%] 3 of 3, cached: 3 ✔
[-        ] process > collectSampleInfo              -
[a6/e04c2d] process > multiQC (sample1)              [100%] 1 of 1, cached: 1 ✔
[icbi/nextNEOpi] Pipeline Complete! You can find your results in /scratch/project/tcr_neoantigen/results/results_kt
WARN: Graphviz is required to render the execution DAG in the given format -- See http://www.graphviz.org for more info.
Error executing process > 'pVACseq (sample1)'

Caused by:
  Process `pVACseq (sample1)` terminated with an error exit status (1)

Command executed:

  pvacseq run \
      --iedb-install-directory /opt/iedb \
      -t 60 \
      -p sample1_vep_phased.vcf.gz \
      -e1 8,9,10,11 \
      -e2 15,16,17,18,19,20,21,22,23,24,25 \
      --normal-sample-name sample1_normal \
      --tumor-purity 1 \
       \
      --netmhc-stab \
      --binding-threshold 500 --top-score-metric median --minimum-fold-change 0.0 --normal-cov 5 --tdna-cov 10 --trna-cov 10 --normal-vaf 0.02 --tdna-vaf 0.25 --trna-vaf 0.25 --expn-val 1 --maximum-transcript-support-level 1 \
      sample1_vep_somatic_gx.vcf.gz sample1_tumor DPB1*05:01 NetMHCpan NetMHCpanEL MHCflurry MHCflurryEL NetMHCIIpan NetMHCIIpanEL ./
  
  if [ -e ./MHC_Class_I/sample1_tumor.filtered.tsv ]; then
      mv ./MHC_Class_I/sample1_tumor.filtered.tsv ./MHC_Class_I/sample1_tumor_DPB1*05:01.filtered.tsv
  fi
  if [ -e ./MHC_Class_I/sample1_tumor.all_epitopes.tsv ]; then
      mv ./MHC_Class_I/sample1_tumor.all_epitopes.tsv ./MHC_Class_I/sample1_tumor_DPB1*05:01.all_epitopes.tsv
  fi
  if [ -e ./MHC_Class_II/sample1_tumor.filtered.tsv ]; then
      mv ./MHC_Class_II/sample1_tumor.filtered.tsv ./MHC_Class_II/sample1_tumor_DPB1*05:01.filtered.tsv
  fi
  if [ -e ./MHC_Class_II/sample1_tumor.all_epitopes.tsv ]; then
      mv ./MHC_Class_II/sample1_tumor.all_epitopes.tsv ./MHC_Class_II/sample1_tumor_DPB1*05:01.all_epitopes.tsv
  fi

Command exit status:
  1

Command output:
  Warning: Proximal variant is not a missense mutation and will be skipped: chr1 1050069
  Warning: Proximal variant is not a missense mutation and will be skipped: chr1 1050070
  Warning: Proximal variant is not a missense mutation and will be skipped: chr1 158685246
  Warning: Proximal variant is not a missense mutation and will be skipped: chr1 206635763
  Warning: Proximal variant is not a missense mutation and will be skipped: chr6 16327633
  Warning: Proximal variant is not a missense mutation and will be skipped: chr6 16327684
  Warning: Proximal variant is not a missense mutation and will be skipped: chr12 40415107
  Warning: Proximal variant is not a missense mutation and will be skipped: chr17 6579726
  Warning: Proximal variant is not a missense mutation and will be skipped: chr17 17793784
  Warning: Proximal variant is not a missense mutation and will be skipped: chr17 17793787
  Warning: Proximal variant is not a missense mutation and will be skipped: chr17 19415702
  Warning: Proximal variant is not a missense mutation and will be skipped: chr19 7506092
  Warning: Proximal variant is not a missense mutation and will be skipped: chr20 62415946
  Completed
  Generating Variant Peptide FASTA and Key File
  Completed
  Parsing the Variant Peptide FASTA and Key File
  Completed
  Calculating Manufacturability Metrics
  Completed
  Splitting TSV into smaller chunks
  Splitting TSV into smaller chunks - Entries 1-69
  Completed
  Generating Variant Peptide FASTA and Key Files
  Generating Variant Peptide FASTA and Key Files - Epitope Length 15 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 16 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 17 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 18 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 19 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 20 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 21 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 22 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 23 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 24 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 25 - Entries 1-138
  Completed
  Allele DPB1*05:01 not valid for Method NetMHCIIpan. Skipping.
  Allele DPB1*05:01 not valid for Method NetMHCIIpanEL. Skipping.
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 15 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 16 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 17 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 18 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 19 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 20 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 21 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 22 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 23 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 24 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 25 - Entries 1-138
  No output files were created. Aborting.

Command error:
  Warning: Proximal variant is not a missense mutation and will be skipped: chr17 19415702
  Warning: Proximal variant is not a missense mutation and will be skipped: chr19 7506092
  Warning: Proximal variant is not a missense mutation and will be skipped: chr20 62415946
  Completed
  Generating Variant Peptide FASTA and Key File
  Completed
  Parsing the Variant Peptide FASTA and Key File
  Completed
  Calculating Manufacturability Metrics
  Completed
  Splitting TSV into smaller chunks
  Splitting TSV into smaller chunks - Entries 1-69
  Completed
  Generating Variant Peptide FASTA and Key Files
  Generating Variant Peptide FASTA and Key Files - Epitope Length 15 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 16 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 17 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 18 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 19 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 20 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 21 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 22 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 23 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 24 - Entries 1-138
  Generating Variant Peptide FASTA and Key Files - Epitope Length 25 - Entries 1-138
  Completed
  Allele DPB1*05:01 not valid for Method NetMHCIIpan. Skipping.
  Allele DPB1*05:01 not valid for Method NetMHCIIpanEL. Skipping.
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 15 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 16 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 17 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 18 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 19 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 20 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 21 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 22 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 23 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 24 - Entries 1-138
  Parsing binding predictions for Allele DPB1*05:01 and Epitope Length 25 - Entries 1-138
  No output files were created. Aborting.
  Traceback (most recent call last):
    File "/opt/conda/bin/pvacseq", line 8, in <module>
      sys.exit(main())
    File "/opt/conda/lib/python3.8/site-packages/pvactools/tools/pvacseq/main.py", line 123, in main
      args[0].func.main(args[1])
    File "/opt/conda/lib/python3.8/site-packages/pvactools/tools/pvacseq/run.py", line 175, in main
      pvactools.lib.run_utils.change_permissions_recursive(base_output_dir, 0o755, 0o644)
    File "/opt/conda/lib/python3.8/site-packages/pvactools/lib/run_utils.py", line 97, in change_permissions_recursive
      os.chmod(file, file_mode)
  PermissionError: [Errno 1] Operation not permitted: '/scratch/project_mnt/S0142/results/results_kt/work/d6/18df64b1a4a77800e134dff859a41b/.iedb_install_ok.chck'

Work dir:
  /scratch/project/tcr_neoantigen/results/results_kt/work/d6/18df64b1a4a77800e134dff859a41b

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

i would very much like not to chmod -R 777 this folder so any suggestions on how i could proceed? (it's working with chmod -R 777, but still, it's not good to leave it like that).

**Comment by zktuong** [comment]
Now that i think about it. maybe the issue is with my permissions set to high (currently 775). will change it to 755 and see if it helps.

**Comment by zktuong** [comment]
nope 755 doesn't work

**Comment by zktuong** [comment]
it's related to this https://github.com/griffithlab/pVACtools/pull/625

**Comment by zktuong** [comment]
ok adding `--fakeroot` after `--no-home` seems to alleviate this.


so like in #53 but 

```
    // default singularity run options
    containerOptions = "--no-home --fakeroot"
```
