### ISSUE TITLE
MHCFlurry temp file error

### ISSUE THREAD

**Issue by gilsonmm** [icbi-lab/nextNEOpi#85]
I am running nextNEOpi on wgs data and I am running into an issue with NEOFuse, specifically with MHCFlurry. The sample229_dwn_MHCI_final.log gives me this:

Traceback (most recent call last):
  File "/usr/local/bin/source/build_temp.py", line 122, in <module>
    final_out(inFile, outFile)
  File "/usr/local/bin/source/build_temp.py", line 61, in final_out
    with open(assoc_file) as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: './sample229_dwn/NeoFuse/tmp/MHC_I/sample229_dwn_8_BAZ2A_HSD17B6_1_8.tsv'

I have tried using the fix from issue #25 but it did not work and I have tried running the command within the correct work directory which also does not fix the error, I am not sure what else I can do to fix this.

**Comment by riederd** [comment]
Hi, I think we need more information from you.
Can you post the `.nextflow.log`, your sample sheet, and the contents of the work dir in which the process failed (as tar.gz).

Thanks

**Comment by gilsonmm** [comment]
Hi, apologies for the late response.
.nextflow.log: [.nextflow.log](https://github.com/user-attachments/files/17903880/default.nextflow.log)
sample file: [downsampled_batchFile_BAM.csv](https://github.com/user-attachments/files/17903882/downsampled_batchFile_BAM.csv)
work dir: [sample229_work_dir.tar.gz](https://github.com/user-attachments/files/17904758/sample229_work_dir.tar.gz)

For the work dir i did have to remove the STAR folder in order to be able to download the .tar.gz onto github but the issues I am having I dont think are related to STAR

**Comment by riederd** [comment]
Hi we inspected the files and logs and we think that there is an issue with running to many processes in parallel on your machine so the system won't allow to fork new processes, see `.command.err`:

`/vf/users/gilsonmm/neoantigen/nextNEOpi/work/e8/948844bbecf8fb5c5127455acb0b9e/.command.run: fork: retry: Resource temporarily unavailable`

Can you try to reduce the parallel processes for `NeoFuse`, e.g. `cpus =  6`  (you have 24 now, and your machine has 56 in total)

https://github.com/icbi-lab/nextNEOpi/blob/f6300dd1eb8e1db07f4ed2f3dba0ae56f2da5d70/conf/process.config#L181

@abyssum also suggests to check if you have any special GPU (cuda) settings for singularity that might interfere with `tensorflow` that is bundled with the `NeoFuse` image

**Comment by gilsonmm** [comment]
I was able to get it working with reducing the parallel processes! Thank you!

**Comment by gilsonmm** [comment]
I was able to get it working with reducing the parallel processes! Thank you!

**Comment by riederd** [comment]
Great, glad we could help
